channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.10.0
  - cloudpickle==2.2.1
  - numpy==1.26.0
  - packaging==21.3
  - psutil==5.9.0
  - pyyaml==6.0
  - scikit-learn==1.4.0
  - scipy==1.11.4
name: mlflow-env
