path:
    Home: ../
    Bronze: data/Bronze/
    Silver: data/Silver/
    Gold: data/Gold/
    Artefactos: artefactos/
    
data_files:
    Bronze: GOVMS_BA_PRED_ANON.tab
    Silver: Silver_data.csv
    Gold: Gold_data.csv
    
model_files:
    
    Log_metrics: Log_metrics.txt
    Model_name: Model.pkl
    
    
    
    