dtypes:
    'CONT_RUT': 'int'
    'CONT_DV': 'object'
    'campo_1': 'object'
    'campo_2': 'object'
    'campo_3': 'object'
    'campo_4': 'object'
    'campo_5': 'object'
    'campo_6': 'object'
    'campo_7': 'object'
    'campo_8': 'object'
    'campo_9': 'object'
    'campo_10': 'object'
    'campo_11': 'object'
    'campo_12': 'object'
    'campo_13': 'object'
    'campo_14': 'object'
    'campo_15': 'object'
    'campo_16': 'object'
    'campo_17': 'object'
    'campo_18': 'object'
    'campo_19': 'object'
    'campo_20': 'object'
    'campo_21': 'object'
    'campo_22': 'float'
    'campo_23': 'float'
    'campo_24': 'float'
    'campo_25': 'float'
    'campo_26': 'float'
    'campo_27': 'float'
    'campo_28': 'float'
    'campo_29': 'float'
    'campo_30': 'object'
    'campo_31': 'object'
    'campo_32': 'object'
    'campo_33': 'object'
    'campo_34': 'object'
    'campo_35': 'float'
    'campo_36': 'object'
    'campo_37': 'float'
    'campo_38': 'object'
    'campo_39': 'float'
    'campo_40': 'object'
    'campo_41': 'object'
    'campo_42': 'float'
    'campo_43': 'object'
    'campo_44': 'object'
    'campo_45': 'object'
    'campo_46': 'object'
    'campo_47': 'object'
    'campo_48': 'object'
    'campo_49': 'object'
    'campo_50': 'object'
    'campo_51': 'object'
    'campo_52': 'object'
    'campo_53': 'object'
    'campo_54': 'object'
    'campo_55': 'object'
    'campo_56': 'object'
    'campo_57': 'float'
    'campo_58': 'float'
    'campo_59': 'float'
    'campo_60': 'float'
    'campo_61': 'float'
    'campo_62': 'float'
    'campo_63': 'object'
    'campo_64': 'object'
    'campo_65': 'float'
    'campo_66': 'float'
    'campo_67': 'float'
    'campo_68': 'float'
    'campo_69': 'float'
    'campo_70': 'float'
    'campo_71': 'float'
    'campo_72': 'float'
    'campo_73': 'float'
    'campo_74': 'float'
    'campo_75': 'float'
    'campo_76': 'float'
    'campo_77': 'float'
    'campo_78': 'float'
    'campo_79': 'float'
    'campo_80': 'float'
    'campo_81': 'float'
    'campo_82': 'float'
    'campo_83': 'float'
    'campo_84': 'float'
    'campo_85': 'float'
    'campo_86': 'float'
    'campo_87': 'float'
    'campo_88': 'float'
    'campo_89': 'float'
    'campo_90': 'float'
    'campo_91': 'float'
    'campo_92': 'float'
    'campo_93': 'float'
    'campo_94': 'float'
    'campo_95': 'float'
    'campo_96': 'float'
    'campo_97': 'object'
    'campo_98': 'float'
    'campo_99': 'float'
    'campo_100': 'float'
    'campo_101': 'float'
    'campo_102': 'float'
    'campo_103': 'object'




